import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import NavBar from '../components/nav/navbar';
import Banner from '../components/banner/banner';
import Card from '../components/card/card';
import SectionCards from '../components/card/section-cards';

import { getVideos } from '../lib/videos';

export default function Home() {
  const videos = getVideos();
  return (
    <div className={styles.container}>
      <Head>
        <title>NextFlix | Clone tutorial</title>
        <meta name='description' content='Generated by create next app' />
        rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <Banner
        title='Dune'
        subTitle='very sandy and spicy'
        imgUrl='https://pxlbbq.com/wp-content/uploads/2019/02/Dune-Image-du-film.jpg'
        year='1984'
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title='Disney' videos={videos} size='large' />
        <SectionCards title='Watch it again' videos={videos} size='small' />
        <SectionCards title='Travel' videos={videos} size='small' />
        <SectionCards title='Productivity' videos={videos} size='medium' />
        <SectionCards title='Popular' videos={videos} size='small' />
      </div>
    </div>
  );
}
